import Link from 'next/link';import Image from 'next/image';import {guides,specialties} from '@/lib/data';import {SectionHead} from '@/components/ui';import AdvisorSearch from '@/components/Search';import {ArrowRight,Check,Compass,MessagesSquare,ShieldCheck,Sparkles} from 'lucide-react';
export default function Home(){return <>
 <section className="hero"><div className="hero-inner"><p className="kicker"><span/> Independent guidance, thoughtfully matched</p><h1>Find a financial advisor<br/><em>you can trust.</em></h1><p className="hero-copy">Explore experienced financial professionals, compare their expertise, and find an advisor who fits your financial goals.</p><div className="hero-actions"><Link className="btn" href="/match">Find an Advisor <ArrowRight size={17}/></Link><Link className="text-link" href="/for-advisors">I’m a Financial Advisor</Link></div><AdvisorSearch/><div className="trust-line"><span><ShieldCheck size={16}/> Verified profiles</span><span><Check size={16}/> Transparent fees</span><span><Check size={16}/> No cost to search</span></div></div></section>
 <section className="intro section"><div className="intro-number">01</div><div><p className="kicker">A more considered way to choose</p><h2>Expertise matters.<br/><em>The right fit matters more.</em></h2></div><div><p>We bring clarity to the search by helping you compare the things that actually matter: credentials, approach, fees, and experience.</p><Link href="/advisors">Explore our standards <ArrowRight size={16}/></Link></div></section>
 <section className="section"><SectionHead kicker="Explore by expertise" title="Guidance for every financial chapter" copy="Start with what’s on your mind. We’ll help you find advisors with the experience to meet you there."/><div className="specialty-grid">{specialties.slice(0,6).map((s,i)=><Link href={`/advisors?specialty=${encodeURIComponent(s)}`} key={s}><span>0{i+1}</span><div>{s}</div><ArrowRight/></Link>)}</div></section>
 <section className="process section"><div><p className="kicker">Your match, made thoughtfully</p><h2>A clearer path to<br/><em>financial confidence.</em></h2><p>Answer a few focused questions and discover advisors whose expertise and working style align with your needs.</p><Link className="btn cream" href="/match">Start your match <ArrowRight size={17}/></Link></div><div className="steps">{[[Compass,'Tell us what matters','Share your goals, preferences, and how you like to work.'],[Sparkles,'Review thoughtful matches','See advisors selected for their relevant experience and fit.'],[MessagesSquare,'Start a conversation','Connect directly. No pressure, no obligation.']].map(([Icon,t,c],i)=><div className="step" key={t as string}><span>0{i+1}</span><Icon/><div><h3>{t as string}</h3><p>{c as string}</p></div></div>)}</div></section>
 <section className="section guides"><SectionHead kicker="Advisor Registry journal" title="Make sense of your money" copy="Clear perspectives for better financial decisions—written to inform, never overwhelm." link="/guides"/><div className="guide-grid"><Link className="guide-card lead" href={`/guides/${guides[0].slug}`}><Image src="/images/editorial-planning.png" alt="An advisor and client reviewing a financial plan" fill/><div><span>{guides[0].category}</span><h3>{guides[0].title}</h3><p>{guides[0].excerpt}</p><small>{guides[0].time}</small></div></Link>{guides.slice(1,3).map(g=><Link className="guide-card mini" href={`/guides/${g.slug}`} key={g.slug}><div className="guide-pattern"/><div><span>{g.category}</span><h3>{g.title}</h3><p>{g.excerpt}</p><small>{g.time}</small></div></Link>)}</div></section>
 <section className="final-cta"><p className="kicker">Your next move starts here</p><h2>Find guidance that<br/><em>feels right.</em></h2><p>Tell us what you’re working toward. We’ll help you find an advisor who can help you get there.</p><AdvisorSearch/></section>
 </>}
