import Link from 'next/link';
import {BarChart3,Bookmark,Compass,LayoutDashboard,MessageSquare,Settings,Star,UserRound,Users,type LucideIcon} from 'lucide-react';
import {advisors} from '@/lib/data';import {AdvisorCard} from './ui';
type Role='client'|'advisor'|'admin';type NavItem=[LucideIcon,string];
export default function Dashboard({role='client'}:{role?:Role}){
 const nav:NavItem[]=role==='client'?[[LayoutDashboard,'Overview'],[Bookmark,'Saved advisors'],[Compass,'Searches'],[MessageSquare,'Consultations'],[Settings,'Settings']]:role==='advisor'?[[LayoutDashboard,'Overview'],[UserRound,'Profile'],[Users,'Leads'],[Star,'Reviews'],[BarChart3,'Analytics'],[Settings,'Settings']]:[[LayoutDashboard,'Overview'],[Users,'Advisors'],[UserRound,'Users'],[Star,'Reviews'],[MessageSquare,'Leads'],[Settings,'Guides']];
 const stats:(string|number)[][]=role==='client'?[[3,'Saved advisors'],[2,'Consultations'],[5,'Recommended']]:role==='advisor'?[[284,'Profile views'],[18,'New leads'],[7,'Consultations'],['92%','Profile complete']]:[[1284,'Total users'],[215,'Advisors'],[18,'Pending review'],[421,'Reviews']];
 return <div className="dash-shell"><aside><div className="dash-role">{role} workspace</div>{nav.map(([Icon,label])=><Link href="#" className={label==='Overview'?'active':''} key={label}><Icon/>{label}</Link>)}</aside><section className="dash-main"><div className="dash-head"><div><p className="kicker">{role==='client'?'Your financial journey':role==='advisor'?'Practice overview':'Platform operations'}</p><h1>Good morning, <em>{role==='admin'?'Alex':role==='advisor'?'Amara':'Jordan'}.</em></h1></div><button className="btn small">{role==='client'?'Find an advisor':role==='advisor'?'View profile':'Add guide'}</button></div><div className="stats">{stats.map(([number,label])=><div key={label}><span>{label}</span><strong>{number}</strong><small>↑ 12% this month</small></div>)}</div>{role==='client'?<><h2>Recommended for you</h2><div className="advisor-grid">{advisors.slice(0,2).map(a=><AdvisorCard key={a.slug} a={a}/>)}</div></>:<div className="dash-grid"><div className="chart-card"><div><h3>{role==='advisor'?'Profile activity':'Platform growth'}</h3><select><option>Last 30 days</option></select></div><div className="chart-bars">{[35,48,40,62,54,73,67,85,76,92,82,96].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div></div><div className="activity"><h3>{role==='advisor'?'Recent leads':'Pending approvals'}</h3>{advisors.slice(0,4).map((a,i)=><div key={a.slug}><span className="avatar sm">{a.initials}</span><p><b>{a.name}</b><small>{role==='advisor'?a.specialties[0]:'Advisor profile review'}</small></p><time>{i+1}h</time></div>)}</div></div>}</section></div>;
}
