'use client';
import {useState} from 'react';import {ArrowLeft,ArrowRight,Check,LoaderCircle,Sparkles} from 'lucide-react';import {advisors} from '@/lib/data';import {AdvisorCard} from './ui';

const steps=[
 {q:'What are you looking for help with?',sub:'Choose all that apply.',opts:['Retirement Planning','Investment Advisory','Portfolio Management','Tax Planning','Estate Planning','College Planning','General Financial Planning']},
 {q:'What’s your primary goal?',sub:'Choose the outcome that feels most important right now.',opts:['Build a financial plan','Prepare for retirement','Grow my investments','Reduce my tax burden','Plan for my family','Navigate a life transition']},
 {q:'Where are you located?',sub:'This helps us consider location and registration coverage.',opts:['New York, NY','New Jersey','Connecticut','Elsewhere in the United States']},
 {q:'How would you prefer to work?',sub:'Choose the format you would be most comfortable with.',opts:['In person','Video calls','Phone','No preference']},
 {q:'What matters most to you?',sub:'Select the qualities you value in an advisor.',opts:['Experience','Registration history','Specialization','Location','Communication']}
];

export default function MatchWizard(){
 const [step,setStep]=useState(0);const [answers,setAnswers]=useState<Record<number,string[]>>({});const [loading,setLoading]=useState(false);const [complete,setComplete]=useState(false);
 function toggle(option:string){setAnswers(current=>({...current,[step]:(current[step]||[]).includes(option)?current[step].filter(item=>item!==option):[...(current[step]||[]),option]}))}
 function finish(){setLoading(true);window.setTimeout(()=>{setLoading(false);setComplete(true)},1800)}
 const score=(()=>{let value=78;const all=Object.values(answers).flat();if(all.includes('Investment Advisory'))value+=6;if(all.includes('Portfolio Management'))value+=5;if(all.includes('New York, NY'))value+=4;if(all.includes('Experience'))value+=3;if(all.includes('Registration history'))value+=2;return Math.min(value,98)})();
 if(loading)return <div className="match-loading" role="status" aria-live="polite"><div className="match-spinner"><LoaderCircle/><Sparkles/></div><p className="kicker">Reviewing your preferences</p><h1>Finding your strongest match…</h1><p>Comparing your goals, location, priorities, and preferred way of working.</p><div className="loading-track"><i/></div></div>;
 if(complete){const advisor=advisors[0];return <div className="match-results"><p className="kicker">Your strongest match</p><h1>One advisor stands out for <em>your criteria.</em></h1><p>This result is based on the answers you provided and the public information currently available in Advisor Registry.</p>{advisor?<div className="single-match"><div className="match-score"><strong>{score}%</strong><span>match</span><small>Based on your questionnaire</small></div><AdvisorCard a={advisor}/><div className="match-reasons"><h3>Why this match</h3><ul>{answers[0]?.slice(0,2).map(x=><li key={x}><Check/> Your interest in {x.toLowerCase()}</li>)}<li><Check/> {advisor.years} years of industry experience</li><li><Check/> Registration record available for review</li>{answers[2]?.[0]&&<li><Check/> Location preference: {answers[2][0]}</li>}</ul></div></div>:<div className="empty"><h2>No suitable advisor found</h2><p>We’ll keep your criteria ready as the registry grows.</p></div>}<button className="text-link restart-match" onClick={()=>{setComplete(false);setStep(0);setAnswers({})}}><ArrowLeft/> Retake questionnaire</button></div>}
 const current=steps[step];return <div className="wizard"><div className="wizard-progress"><span>Step {step+1} of {steps.length}</span><div><i style={{width:`${((step+1)/steps.length)*100}%`}}/></div></div><p className="kicker">A thoughtful match starts with you</p><h1>{current.q}</h1><p>{current.sub}</p><div className="options">{current.opts.map(option=><button type="button" className={(answers[step]||[]).includes(option)?'selected':''} onClick={()=>toggle(option)} key={option}><span>{option}</span>{(answers[step]||[]).includes(option)&&<Check/>}</button>)}</div><div className="wizard-nav"><button type="button" disabled={!step} className="text-link" onClick={()=>setStep(value=>value-1)}><ArrowLeft/> Back</button><button type="button" disabled={!answers[step]?.length} className="btn" onClick={()=>step===steps.length-1?finish():setStep(value=>value+1)}>{step===steps.length-1?'Find my advisor':'Continue'} <ArrowRight/></button></div></div>
}
